version: '1.0'
services:
  web:
    container_name: flask-verify
    build: .
    command: flask run --host=0.0.0.0
    volumes:
      - .:/usr/src/app/
    ports:
      - 5001:5000
    env_file:
      - ./.env